// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Username  string
	Password  pgtype.Text
	Createdat pgtype.Timestamptz
}
